parental_control-objs := pc_policy.o pc_config.o cJSON.o pc_app.o pc_utils.o pc_filter.o regexp.o
obj-m := parental_control.o
#KDIR := /home/glinet/work/gl-infra-builder/mt7981/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7981/linux-5.4.188
#TOOS_CHAIN=/home/glinet/work/gl-infra-builder/mt7981/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/bin/aarch64-openwrt-linux-
#
#all:
#	make -C $(KDIR) M=$(PWD) modules CROSS_COMPILE=$(TOOS_CHAIN) ARCH=arm64
#clean:
#	rm -f *.ko *.o *.mod.o *.mod.c *.symvers *.bak *.order *.cmd *.mod .*.cmd
