include $(TOPDIR)/rules.mk

LUCI_TITLE:=MTK WiFi Configuration
LUCI_DEPENDS:=+luci-compat luci
LUCI_PKGARCH:=all

LUA_TARGET:=source

include ../../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
