#!/bin/sh /etc/rc.common
# Copyright © 2020 GL.iNet. All Rights Reserved.

START=90

USE_PROCD=1

start_uart_interface_daemon() {
    local uart_tty uart_baudrate uart_fc
    local ifname

    logger -t otbr-agent "Start otbr-agent on UART interface"

    config_load otbr
    config_get uart_tty otbr uart_tty
    config_get uart_baudrate otbr uart_baudrate
    config_get uart_fc otbr uart_fc
    config_get gpio_rst otbr gpio_rst
    config_get gpio_dfu otbr gpio_dfu
    config_get ifname bbr ifname
    
    # Check if need to upgrade Thread RCP before startup
    local filepath
    filepath=$(ls /etc/openthread/*.gbl 2>/dev/null)
    [ -f "$filepath" -a -n "$(which gl-ot-dfu)" ] && {
        logger -t otbr-agent "Found DFU file $filepath"
        gl-ot-dfu -t -F
    }

    procd_open_instance
    procd_set_param command /usr/sbin/otbr-agent -d 7 -B $ifname -I wpan0 "spinel+hdlc+uart://$uart_tty?uart-baudrate=$uart_baudrate$uart_fc" trel://$ifname
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

start_spi_interface_daemon() {
    local spi_device gpio_sel gpio_int gpio_rst gpio_wake
    local ifname

	logger -t otbr-agent "Start otbr-agent on SPI interface"

    config_load otbr
    config_get spi_device otbr spi_device
    config_get gpio_sel otbr gpio_sel
    config_get gpio_int otbr gpio_int
    config_get gpio_rst otbr gpio_rst
    config_get gpio_wake otbr gpio_wake
    config_get ifname bbr ifname

    [ ! -e "/sys/class/gpio/gpio$gpio_sel" ] && {
        echo $gpio_sel >/sys/class/gpio/export
        echo out >/sys/class/gpio/gpio$gpio_sel/direction
    }

    procd_open_instance
    procd_set_param command /usr/sbin/otbr-agent -d 7 -B $ifname -I wpan0 "spinel+spi://$spi_device?gpio-int-device=/dev/gpiochip0&gpio-int-line=$gpio_int&gpio-reset-device=/dev/gpiochip0&gpio-reset-line=$gpio_rst&no-reset=1&spi-speed=1000000"
	procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_close_instance
}

restore_bbr_interface () {
    local bbr_ifname=$(uci -q get otbr.bbr.ifname)
    local rp_disabled=$(uci -q get repeater.@main[0].disabled)
    if [ "$bbr_ifname" = "wlan-sta0" -a "$rp_disabled" = "1" ]; then
        uci set otbr.bbr.ifname='br-lan'
        uci commit otbr
    fi
}

start_service() {
    restore_bbr_interface
    
    start_uart_interface_daemon
}

service_triggers() {
    procd_add_reload_trigger "otbr"
}
