#!/bin/sh /etc/rc.common
# Copyright © 2020 GL.iNet. All Rights Reserved.

START=99

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/otbr-web -d 7 -I wpan0 -p 8080
    procd_close_instance
}