#!/bin/sh

[ "$(uci -q get glconfig.general.inited)" = "1" ] && exit 0

echo "88 openthread" >>/etc/iproute2/rt_tables
echo "# OpenThread configuration" >>/etc/sysctl.conf
echo "net.core.optmem_max=65536" >>/etc/sysctl.conf
echo "net.ipv6.conf.all.disable_ipv6=0" >>/etc/sysctl.conf
echo "net.ipv6.conf.all.accept_ra=1" >>/etc/sysctl.conf
echo "net.ipv6.conf.default.accept_ra=1" >>/etc/sysctl.conf
echo "net.ipv6.conf.wpan0.accept_ra=1" >>/etc/sysctl.conf
echo "net.ipv6.conf.wpan0.disable_ipv6=0" >>/etc/sysctl.conf
echo "net.ipv6.conf.wpan0.forwarding=1" >>/etc/sysctl.conf
echo "net.ipv6.conf.br-guest.disable_ipv6=1" >>/etc/sysctl.conf
echo "net.ipv6.conf.br-lan.accept_ra=2" >>/etc/sysctl.conf
sysctl -p /etc/sysctl.conf

uci set firewall.@defaults[0].forward='ACCEPT'
uci commit firewall

uci commit firewall

exit 0
